nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  # Getting the error: Cannot redefine settings "constraintsPath" since upgrade from v4.0.0-rc.22 to v4.0.0-rc.27
  # - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
  #   spec: '@yarnpkg/plugin-constraints'

yarnPath: .yarn/releases/yarn-4.0.0-rc.27.cjs
