ignore:
  # The code in this file comes from tabbable: https://github.com/focus-trap/tabbable
  # and has been thoroughly tested already in that library.
  # The reason why it's not a dependency is that using its exported:
  #
  # - `isTabbable` would still require to duplicate some of *tabbable* code
  #   (namely: `candidateSelector` and `getConsistentTabIndex`)
  #
  # - `tabbable` would make findinding a destination way more inefficient
  #   (ie: running `isTabbable` on every trapped element matching `candidateSelector`)
  - 'packages/focus-trap/src/tabbability.ts'
